import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Header } from "./components/Header";
import styles from "../styles/Home.module.css";
import { getProducts, Product } from "./api/products";
import { ProductCard } from "./components/ProductCard";

export async function getStaticProps() {
  return {
    props: {
      products: getProducts(),
    },
  };
}

type HomeProps = { products: Product[] };

const Home: NextPage<HomeProps> = ({ products }) => {
  return (
    <div className="bg-white container mx-auto">
      <Head>
        <title>Bryan Azofeifa Borbon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="mx-auto">
        <header className="text-center lg:py-16 mt-8">
          <h1 className="font-inter font-bold text-5xl text-sky-800">
            Bryan Azofeifa
          </h1>
        </header>
        <div className="text-left mt-14 flex justify-center">
          {products.map((product) => (
            <ProductCard key={product.name} product={product} />
          ))}
        </div>

        <div className="my-8">
          <h3>Latests blog posts</h3>
          <ul>
            <li>
              <h3>How to become a better developer</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation{" "}
              </p>
              <Link href="/">Read more</Link>
            </li>
            <li>
              <h3>My Journey: 14 years of writing code</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation{" "}
              </p>
              <Link href="/">Read more</Link>
            </li>
          </ul>
        </div>

        <div>
          <p>Learn more about me</p>

          <p>
            Subscribe to get new content. Know more <a>here.</a>
          </p>
          <input type="email"></input>
          <button>Subscribe</button>
          <span>I write once a month ❤️️</span>
          <span>No ads.</span>
        </div>
      </main>
    </div>
  );
};

export default Home;
