import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { getProducts, Product } from "../api/products";
import { ProductCard } from "../components/ProductCard";

export async function getStaticProps() {
  return {
    props: {
      products: getProducts(),
    },
  };
}

type HomeProps = { products: Product[] };

const Home: NextPage<HomeProps> = ({ products }) => {
  return (
    <div className="bg-slate-200">
      <Head>
        <title>Bryan Azofeifa Borbon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="text-center lg:pb-16 pt-8 bg-white">
        <h1 className="font-bold text-5xl text-sky-800">Bryan Azofeifa</h1>
        <h3 className="mt-6 text-lg">Helping developers get to the next level 🚀</h3>
      </header>

      <main className="mx-auto">
        <div className="text-left mt-10 flex justify-center">
          {products.map((product) => (
            <ProductCard key={product.name} product={product} />
          ))}
        </div>

        <div className="container mx-auto">
          <div className="my-8">
            <h3 className="text-2xl py-4">Latests blog posts</h3>
            <ul className="flex">
              <li className="w-1/3 border border-solid rounded-md border-slate-300 p-4 mb-4 mr-2">
                <h3 className="text-xl text-sky-800 pb-2">
                  How to become a better developer
                </h3>
                <p>
                  In order to become a better developer, it is important to
                  understand the technologies you use, read code, and learn from
                  others. Additionally, it is beneficial to care about code
                  quality, strive for an error-free mindset...&nbsp;
                  <span className="text-blue-600 underline">
                    <Link href="/">Read more</Link>
                  </span>
                </p>
              </li>
              <li className="w-1/3 border border-solid rounded-md border-slate-300 p-4 mb-4">
                <h3 className="text-xl text-sky-800 pb-2">
                  My Journey: 14 years of writing code
                </h3>
                <p>
                  At 19 years old, I had to create an email address for the
                  first time in order to fill out a university registry
                  form...&nbsp;
                  <span className="text-blue-600 underline">
                    <Link href="/">Read more</Link>
                  </span>
                </p>
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-2xl py-4">Newsletter</h3>
            <p className="py-2">Get notified when new stuff is released! ❤️️</p>
            <div className="border border-solid border-gray-600 inline-block">
              <input
                className="p-2 rounded-sm w-52"
                placeholder="Email"
                type="email"
              ></input>
              <button className="p-2 bg-sky-800 text-white hover:bg-sky-600">Subscribe</button>
            </div>
            <p className="py-2 text-sm">I write once a month.</p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
